services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  prometheus:
    image: 'prom/prometheus:latest'
    container_name: blog-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: 'grafana/grafana:latest'
    container_name: blog-grafana
    ports:
      - '3000:3000'
    environment:
      -  GF_PLUGINS_PREINSTALL=grafana-clock-panel,grafana-polystat-panel
    depends_on:
      - prometheus
